"""
Skill template generators.

Generates skill.md and tool.py content from configuration.
"""

from __future__ import annotations

from datetime import datetime
from typing import List

from .skill_config import SkillConfig


def generate_skill_md(config: SkillConfig) -> str:
    """Generate skill.md content."""
    date = datetime.now().strftime("%Y-%m-%d")
    level_desc = "Family Orchestrator" if config.level == 1 else "Worker Skill"
    parent = f"qa-{config.family}" if config.level == 2 else "qa-super"

    tags = f"[qa, {config.family}, {config.skill_type}, level-{config.level}"
    if config.generate_python:
        tags += ", python-tool"
    tags += "]"

    formatted_name = config.name.replace("qa-", "").replace("-", " ").title()
    output_desc = (
        "Detection report with issue locations"
        if config.skill_type == "detection"
        else "Fixed content"
    )

    content = f"""---
name: {config.name}
description: {config.description} (Level {config.level} skill)
version: 1.0.0
author: QA Team
tags: {tags}
---

# {config.name} (Level {config.level})

## Agent Identity
- **Name:** {formatted_name}
- **Role:** {config.description}
- **Level:** {config.level} ({level_desc})
- **Parent:** {parent}

## Coordination

### Reports To
- {parent} (Level {config.level - 1} orchestrator)

### Input
- LaTeX source files from parent

### Output
- {output_desc}
"""

    if config.generate_python:
        content += f"""
## Python Tool Integration

This skill is backed by Python for deterministic {config.skill_type}:
- **Module:** tool.py
- **Rules:** {len(config.rules)} rules
"""

    if config.rules:
        content += "\n## Detection Rules\n\n"
        content += "| Rule ID | Description |\n"
        content += "|---------|-------------|\n"
        for rule in config.rules:
            content += f"| `{rule}` | {rule.replace('-', ' ').title()} |\n"

    content += f"""
## Mission Statement

{config.description}

## Version History
- **v1.0.0** ({date}): Initial creation
"""
    return content


def generate_tool_py(config: SkillConfig) -> str:
    """Generate tool.py content."""
    rules_dict = _format_rules_dict(config.rules)

    return f'''"""
Python tool for {config.name}.

Auto-generated by insert_qa_skill.
"""

from pathlib import Path
from typing import List, Dict, Any


def run_detection(file_path: str, content: str = None) -> List[Dict[str, Any]]:
    """
    Run detection on file.

    Args:
        file_path: Path to file
        content: Optional content

    Returns:
        List of issue dictionaries
    """
    if content is None:
        path = Path(file_path)
        if not path.exists():
            return [{{"error": f"File not found: {{file_path}}"}}]
        content = path.read_text(encoding="utf-8")

    # TODO: Implement detection logic
    return []


def get_rules() -> Dict[str, str]:
    """Get available detection rules."""
    return {{
{rules_dict}
    }}


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        results = run_detection(sys.argv[1])
        for r in results:
            print(r)
'''


def _format_rules_dict(rules: List[str]) -> str:
    """Format rules as dictionary entries."""
    if not rules:
        return "        # No rules defined"
    lines = []
    for rule in rules:
        desc = rule.replace("-", " ").title()
        lines.append(f'        "{rule}": "{desc}",')
    return "\n".join(lines)
